import { lazy } from "react";
import { LayoutDashboard } from "lucide-react";
import { z } from "zod";

import { createModule } from "@fancydashboard/sdk/plugins/createModule";
import type { ModuleManifest } from "@fancydashboard/sdk/plugins/types";

const GlobalSettings = lazy(() => import("./GlobalSettings"));
const Widget = lazy(() => import("./Widget"));
const WidgetConfigSchema = z.object({}).passthrough();

export default createModule({
  id: "{{pluginName}}",
  version: "1.0.0",
  metadata: {
    name: "{{pluginName}}",
    summary: "A community module for FancyDashboard.",
    description: "A community module generated by create-fancy-community.",
    author: {
      name: "FancyDashboard Community",
      email: null,
      github: null,
    },
    website: null,
    license: "MIT",
    repository: null,
    category: "other",
    tags: [],
    tier: "community",
  },
  icon: {
    type: "react-icon",
    component: LayoutDashboard,
  },
  globalSettings: GlobalSettings,
  globalPermissions: [],
  widgets: [
    {
      id: "{{pluginName}}",
      name: "{{pluginName}} Widget",
      description: "Default widget for {{pluginName}}.",
      component: Widget,
      settingsComponent: null,
      permissions: [],
      grid: {
        defaultW: 2,
        defaultH: 2,
        minW: 1,
        minH: 1,
        maxW: 4,
        maxH: 4,
        lockAspectRatio: false,
      },
      config: {
        schema: WidgetConfigSchema,
        default: {},
      },
    },
  ],
} satisfies ModuleManifest);
